### PR TITLE
emit event for audit.  Closes #3.

### LINKED ISSUE #3: Emit audit message
NLC-handled commands cannot pass through our normal path of being captured by listener middleware.  In order to capture them, we need to issue an emit that the audit package can respond to.

### PR DESCRIPTION
**Pull request by ngawor**

### CODE REVIEW

**Comment by jlpadilla** [comment]
What exaclty do we want to capture?  With this change we will be capturing everything that goes through NLC, weather the code decides to act on it or not.

If we only want to capture the statements that NLC decides to act on, then a better place to add the emit is at these 2 locations.
- https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/blob/master/src/scripts/nlc.confidence.high.js#L78
- https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/blob/master/src/scripts/nlc.confidence.med.js#L105

**Comment by ngawor** [comment]
I would think we actually want to capture those things we have already decided were addressed to the bot -- which is where this is.  If we decide to capture only high and medium confidence we are missing out on statements we didn't understand, which is one of the things we wanted to capture.  @chambrid may have a different opinion.

**Comment by chambrid** [comment]
We want to capture anything where the user has addressed the bot.

**Comment by jlpadilla** [comment]
OK, thanks for the clarification.

**Comment by jlpadilla** [comment]
+1

**Pull request merged**
